# kitty.conf

# Colors 
background #000000

# Environment variables
env TERM=xterm-256color

# Font
font_family Hack Nerd Font
font_size 18.0

bold_font Hack Nerd Font
italic_font Hack Nerd Font
bold_italic_font Hack Nerd Font
